################################################################################
# ENVIRONMENT TEMPLATES
################################################################################

# can't merge arrays in YAML so we have to duplicate stuff between 36 and 37
# and include all variables that are relevant across all operating systems
env_py36: &env_py36
  env:
    - PYTHON_VERSION=3.6.8
    - PY_MM=36
    - TOXENV=py${PY_MM}
    - PATH=/c/Python${PY_MM}:/c/Python${PY_MM}/Scripts:$PATH
env_py37: &env_py37
  env:
    - PYTHON_VERSION=3.7.4
    - PY_MM=37
    - TOXENV=py${PY_MM}
    - PATH=/c/Python${PY_MM}:/c/Python${PY_MM}/Scripts:$PATH


################################################################################
# OS JOB TEMPLATES
################################################################################

# osx_base_job: &osx_base_job
#   os: osx
#   osx_image: xcode9.2
#   language: sh
#   before_install:
#     # install things that take longer than 10min with -v for travis to not stop!
#     - brew install -v gcc
#     - brew install ceres-solver
#     - wget https://github.com/opencv/opencv/archive/3.4.6.zip
#     - unzip 3.4.6.zip
#     - cd opencv-3.4.6
#     - mkdir -p build
#     - cd build
#     - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_LIST=core,highgui,videoio,imgcodecs,imgproc,video ..
#     - make -j8
#     - make install
#     - cd ../..
#     - brew upgrade pyenv
#     - export PATH="/Users/travis/.pyenv/shims:${PATH}"
#     - pyenv install -s 3.6.8
#     - pyenv install -s 3.7.4
#   install:
#     - mkdir -p wheelhouse
#     - pyenv global 3.6.8
#     - pip wheel --no-deps -w wheel_test .
#     - pip install tox
#     - tox --installpkg wheel_test/*.whl -e py36
#     - mv wheel_test/*.whl wheelhouse/

#     - pyenv global 3.7.4
#     - pip wheel --no-deps -w wheel_test .
#     - pip install tox
#     - tox --installpkg wheel_test/*.whl -e py37
#     - mv wheel_test/*.whl wheelhouse/

# osx_new_job: &osx_new_job
#   os: osx
#   osx_image: xcode11.2
#   language: sh
#   before_install:
#     - brew install ceres-solver opencv@3
#     - brew upgrade pyenv
#     - export PATH="/Users/travis/.pyenv/shims:${PATH}"
#     - pyenv install -s 3.6.8
#     - pyenv install -s 3.7.4
#   install:
#     - mkdir -p wheelhouse
#     - pyenv global 3.6.8
#     - pip wheel --no-deps -w wheel_test .
#     - pip install tox
#     - tox --installpkg wheel_test/*.whl -e py36
#     - mv wheel_test/*.whl wheelhouse/

#     - pyenv global 3.7.4
#     - pip wheel --no-deps -w wheel_test .
#     - pip install tox
#     - tox --installpkg wheel_test/*.whl -e py37
#     - mv wheel_test/*.whl wheelhouse/

# osx_13: &osx_13
#   os: osx
#   osx_image: xcode10.1
#   language: sh
#   before_install:
#     - brew install ceres-solver opencv@3
#     - brew upgrade pyenv
#     - export PATH="/Users/travis/.pyenv/shims:${PATH}"
#     - pyenv install -s 3.6.8
#     - pyenv install -s 3.7.4
#   install:
#     - mkdir -p wheelhouse
#     - pyenv global 3.6.8
#     - pip wheel --no-deps -w wheel_test .
#     - pip install tox
#     - tox --installpkg wheel_test/*.whl -e py36
#     - mv wheel_test/*.whl wheelhouse/

#     - pyenv global 3.7.4
#     - pip wheel --no-deps -w wheel_test .
#     - pip install tox
#     - tox --installpkg wheel_test/*.whl -e py37
#     - mv wheel_test/*.whl wheelhouse/

# stages:
#   - setup
#   - build

win_dependency_job: &win_dependency_job
  os: windows
  language: sh
  # stage: setup
  # workspaces:
  #   create:
  #     name: dependencies
  #     paths:
  #       - dependencies
  cache:
    directories:
      - dependencies
  script:
    - ls dependencies
    - true && [ -d "dependencies/ceres-solver" ] && echo "Using cached dependencies!" || ./.travis/win_setup_dependencies.sh
  

    
win_base_job: &win_base_job
  os: windows
  language: sh
  # stage: build
  # workspaces:
  #   use: dependencies
  cache:
    directories:
      - dependencies
  before_install:
    # Set build parameters
    - export EIGEN_DIR=`pwd`/dependencies/eigen
    - export OPENCV_DIR=`pwd`/dependencies/opencv
    - export CERES_DIR=`pwd`/dependencies/ceres-solver

  install:
    - choco install vcredist2010
    - choco install python --version 3.6.8
    - PATH=/c/Python36:/c/Python36/Scripts:$PATH
    - python -m pip install -U pip
    - pip wheel --no-deps -w wheel_test .
  before_deploy:
    - pip install numpy opencv-python
    - pip install wheel_test/*.whl
    - pip install pytest
    - pytest tests
    # - pip install tox
    # - tox --installpkg wheel_test/*.whl -e py36
    # - mv wheel_test/*.whl wheelhouse/

    # - choco install python --version 3.7.4
    # - PATH=/c/Python37:/c/Python37/Scripts:$PATH
    # - pip wheel --no-deps -w wheel_test .
    # - pip install tox
    # - tox --installpkg wheel_test/*.whl -e py37
    # - mv wheel_test/*.whl wheelhouse/

# ubuntu_base_job: &ubuntu_base_job
#   os: linux
#   language: sh
#   services: docker
#   before_install:
#     - docker pull pupillabs/pupil-detectors:linux-latest
#   install:
#     - chmod +x ./.travis/linux_build_wheels.sh
#     - >
#       docker run --rm
#       -v `pwd`:/io
#       pupillabs/pupil-detectors:linux-latest
#       /io/.travis/linux_build_wheels.sh
  

################################################################################
# DEFINE JOB MATRIX
################################################################################

matrix:
  include:
    # - name: "OSX 10.12 (xcode9.2)"
    #   <<: *osx_base_job

    # - name: "OSX 10.14 (xcode11.2)"
    #   <<: *osx_new_job

    # - name: "OSX 10.13 (xcode10.1)"
    #   <<: *osx_13
    - name: "Setup Windows dependencies"
      <<: *win_dependency_job

    - name: "Build Windows wheels"
      <<: *win_base_job

    # - name: "Ubuntu (manylinux)"
    #   <<: *ubuntu_base_job


################################################################################
# RUN AND DEPLOY (OS INDEPENDENT)
################################################################################


script:
  - ls wheel_test

# script:
#   - tox --installpkg ./dist/pupil_apriltags*.whl

deploy_template: &deploy_template
  skip_cleanup: true
  all_branches: true


deploy:
  - provider: releases
    <<: *deploy_template
    api_key: $GitHubOAUTH
    file_glob: true
    file: "./wheel_test/*"
#   - provider: script
#     <<: *deploy_template
#     script: bash ./.travis/pypi_deploy.sh