# This is only used for building manylinux wheels in a docker image.

name: "Ubuntu (manylinux)"
os: linux
language: sh
services: docker

before_install:
  - docker pull pupillabs/pupil-detectors:linux-latest

install:
  - chmod +x ./.travis/linux_build_wheels.sh
  - >
    docker run --rm
    -v `pwd`:/io
    pupillabs/pupil-detectors:linux-latest
    /io/.travis/linux_build_wheels.sh
  
before_script:
  - ls wheelhouse
  - NUM_WHEELS=`ls -f wheelhouse/*.whl | wc -l`
  - echo "Built ${NUM_WHEELS} wheels."

script:
  # check that we have the right number of wheels built!
  - "[ ${NUM_WHEELS} -eq 2 ] || exit 1"

deploy_template: &deploy_template
  skip_cleanup: true
  on:
    branch: master

deploy:
  - provider: releases
    <<: *deploy_template
    api_key: $GitHubOAUTH
    file_glob: true
    file: "./wheelhouse/*"
    draft: true
    name: "Automated wheel building test"
    body: "Uploaded from travis"

#   - provider: script
#     <<: *deploy_template
#     script: bash ./.travis/pypi_deploy.sh