################################################################################
# ENVIRONMENT TEMPLATES
################################################################################

# can't merge arrays in YAML so we have to duplicate stuff between 36 and 37
# and include all variables that are relevant across all operating systems
env_py36: &env_py36
  env:
    - PYTHON_VERSION=3.6.8
    - PY_MM=36
    - TOXENV=py${PY_MM}
    - PATH=/c/Python${PY_MM}:/c/Python${PY_MM}/Scripts:$PATH
env_py37: &env_py37
  env:
    - PYTHON_VERSION=3.7.4
    - PY_MM=37
    - TOXENV=py${PY_MM}
    - PATH=/c/Python${PY_MM}:/c/Python${PY_MM}/Scripts:$PATH


################################################################################
# OS JOB TEMPLATES
################################################################################

osx_base_job: &osx_base_job
  os: osx
  osx_image: xcode8.3
  language: sh
  before_install:
    - brew install ceres-solver
    - wget https://github.com/opencv/opencv/archive/3.4.6.zip
    - unzip 3.4.6.zip
    - cd opencv-3.4.6
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_LIST=core,highgui,videoio,imgcodecs,imgproc,video ..
    - make -j8
    - make install
    - cd ../..
    - brew upgrade pyenv
    - pyenv install -s 3.6.8
    - pyenv install -s 3.7.4
  install:
    - pyenv global 3.6.8
    - pip wheel --no-deps -w wheel_test .
    - tox --installpkg wheel_test/*.whl -e py36
    - mv wheel_test/*.whl wheelhouse/

    - pyenv global 3.7.4
    - pip wheel --no-deps -w wheel_test .
    - tox --installpkg wheel_test/*.whl -e py37
    - mv wheel_test/*.whl wheelhouse/

    
win_base_job: &win_base_job
  os: windows
  language: sh
  before_install:
    - git clone https://github.com/Microsoft/vcpkg.git
    - cd vcpkg
    - powershell ./bootstrap-vcpkg.bat
    - ./vcpkg install opencv3 ceres eigen
    - export -DCMAKE_TOOLCHAIN_FILE=`pwd`/scripts/buildsystems/vcpkg.cmake


    - choco install python --version 3.6.8
    - pip wheel --no-deps -w wheel_test .
    - tox --installpkg wheel_test/*.whl -e py36
    - mv wheel_test/*.whl wheelhouse/

    - choco install python --version 3.7.4
    - pip wheel --no-deps -w wheel_test .
    - tox --installpkg wheel_test/*.whl -e py37
    - mv wheel_test/*.whl wheelhouse/

ubuntu_base_job: &ubuntu_base_job
  os: linux
  language: sh
  services: docker
  before_install:
    - docker pull pupillabs/pupil-detectors:linux-latest
  install:
    - chmod +x ./.travis/linux_build_wheels.sh
    - >
      docker run --rm
      -v `pwd`:/io
      pupillabs/pupil-detectors:linux-latest
      /io/.travis/linux_build_wheels.sh
  

################################################################################
# DEFINE JOB MATRIX
################################################################################

matrix:
  include:
    - name: "OSX 10.12 (xcode8.3)"
      <<: *osx_base_job

    - name: "Windows"
      <<: *win_base_job

    # - name: "Ubuntu (manylinux)"
    #   <<: *ubuntu_base_job


################################################################################
# RUN AND DEPLOY (OS INDEPENDENT)
################################################################################


script:
  - ls wheelhouse

# script:
#   - tox --installpkg ./dist/pupil_apriltags*.whl

# deploy_template: &deploy_template
#   on:
#     tags: true
#     branch: master
#   skip_cleanup: true

# deploy:
#   - provider: releases
#     <<: *deploy_template
#     api_key: $GitHubOAUTH
#     file_glob: true
#     file: "./dist/pupil_apriltags*"
#   - provider: script
#     <<: *deploy_template
#     script: bash ./.travis/pypi_deploy.sh